---
apiVersion: v1
kind: Pod
metadata:
  name: pg-client-prem
spec:
  containers:
    - image: bitnami/postgresql:12.15.0-debian-11-r8
      name: postgresql-prem
      env:
      - name: ALLOW_EMPTY_PASSWORD
        value: "yes"