apiVersion: v1
kind: Service
metadata:
  name: postgres-prem-headless-svc
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: postgresql-prem
    port: 5432
    targetPort: postgresql-prem
    protocol: TCP 
  selector:
    app: postgres-prem