apiVersion: v1
kind: Service
metadata:
  name: pg-ha-test-headless-svc
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: pg-ha-test
    port: 5432
    targetPort: postgresql
    protocol: TCP 
  selector:
    app: postgres