apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: od-ha-val
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: od-ha-val.webdiscode.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: od-ha-val
            port:
              number: 8069
  tls:
  - hosts:
    - od-ha-val.webdiscode.com
    secretName: od-ha-val.webdiscode.com-tls