apiVersion: v1
kind: Service
metadata:
  name: odoo-ha-test
spec:
  selector:
    workload.user.cattle.io/workloadselector: deployment-default-odoo-ha-test
  ports:
    - protocol: TCP
      targetPort: odoo-ha-test
      port: 8069
      name: odoo-ha-test