apiVersion: apps/v1
kind: Deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-od-ha
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-default-od-ha
    spec:
      affinity: {}
      containers:
      - env:
        - name: ODOO_DATABASE_HOST
          value: 194.163.128.19
        - name: ODOO_DATABASE_PORT_NUMBER
          value: "31440"
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: ODOO_DATABASE_ADMIN_PASSWORD
          value: WbrTpN3g7q
        image: bitnami/odoo:16.0.20230515-debian-11-r8
        imagePullPolicy: IfNotPresent
        name: container-0
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2023-06-07T01:33:24Z"
    lastUpdateTime: "2023-06-07T03:58:23Z"
    message: ReplicaSet "od-ha-5ff569f678" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 27
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
