apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: od-ha-test
  labels:
    app: od-ha-test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
