apiVersion: v1
kind: Service
metadata:
  name: pgpool-svc-ha-test-external-ha-test
spec:
  type: NodePort
  ports:
    - name: pg-ha-test
      port: 5432
      targetPort: postgresql
      protocol: TCP
  selector:
    app: pgpool
