apiVersion: v1
kind: Service
metadata:
  name: pgpool-svc-ha-test
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: postgres-ha-test
      port: 5432
      targetPort: postgresql
      protocol: TCP
      nodePort: null
  selector:
    app: pgpool