apiVersion: v1
kind: Service
metadata:
  name: pgpool-prem-svc
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: postgresql-prem
      port: 5432
      targetPort: postgresql-prem
      protocol: TCP
      nodePort: null
  selector:
    app: pgpool