apiVersion: v1
kind: Service
metadata:
  name: pgpool-svc-external
spec:
  type: NodePort
  ports:
    - name: postgres-ha-test
      port: 5432
      targetPort: postgresql
      protocol: TCP
  selector:
    app: pgpool
